@startgantt
sunday are closed
saturday are coloured LightBlue

2023-10-13 to 2023-10-13 are colored in LightGreen
[Presentacion de asignatura] lasts 3 days
[PEC 01] lasts 13 days

[Lectura enunciado actividad 1] lasts 1 days
[Decision de formato de TFM] lasts 1 days
[Maquetacion de TFM en LaTeX] lasts 4 days
[Elaboración de índice] lasts 2 days
[Refinamiento de TFM] lasts 1 days
[Prototype design8] lasts 15 days
[Prototype design9] lasts 15 days
[Prototype design10] lasts 15 days
[Prototype design11] lasts 15 days
[Prototype design12] lasts 15 days

[Test prototype] lasts 10 days

Project starts 2023-9-27
[Presentacion de asignatura] ends 2023-9-29
[PEC 01] ends 2023-10-14
[PEC 01] is coloured in IndianRed
[Lectura enunciado actividad 1] ends 2023-9-30
[Decision de formato de TFM] starts at [Lectura enunciado actividad 1]'s end
[Maquetacion de TFM en LaTeX] starts at [Decision de formato de TFM]'s end
[Elaboración de índice] starts 2 working days after [Decision de formato de TFM]'s end and lasts 2 days
[Refinamiento de TFM] starts at [Elaboración de índice]'s end
[Prototype design8] lasts 15 days
[Prototype design9] lasts 15 days
[Prototype design10] lasts 15 days
[Prototype design11] lasts 15 days
[Prototype design12] lasts 15 days
[Test prototype] ends 2023-10-14
@endgantt

@startgantt

saturday are closed
sunday are closed
2022-07-04 to 2022-07-15 is closed

Project starts 2022-06-27
[task1] starts at 2022-06-27 and lasts 1 week
[task2] starts 2 working days after [task1]'s end and lasts 3 days

@endgantt
